server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn_activiti?nullCatalogMeansCurrent=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    database-schema-update: true
